version: '3.1'
services: 
  cf-backend:
    container_name: cf-backend
    build: ./app
    command: npm start
    ports:
      - "4399:4099"
    networks:
      - cf_net
    volumes:
      - /usr/src/app/node_modules
      - ./app:/usr/src/app/
    depends_on: 
      - cfdb
    environment:
      DB_URL=${MONGO_DB_URL}
      PORT=4099
    restart: always
    working_dir: /usr/src/app
  cfdb:
    image: 'mongo'
    container_name: cfdb
    volumes:
      - ./mongo-data:/data/db
    environment: 
      - MONGO_INITDB_DATABASE=cf
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    
